name: Bump version
on:
  push:
    branches:
      - main
jobs:
  tag:
    name: bump tags
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch

  build_image:
    needs: tag
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Check new tags
      run: echo ${{ needs.tag.outputs.new_tag }}
    - name: Check tag
      run: echo ${{ needs.tag.outputs.tag }}

    - run: |
        DOCKER_IMAGE=ghcr.io/${{ github.repository }}
        VERSION=edge
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/}
        elif [[ $GITHUB_REF == refs/heads/* ]]; then
          BRANCH=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
          if [[ $BRANCH == main ]]; then
            VERSION=latest
          elif [[ $BRANCH == devel ]]; then
            VERSION=stage
          fi
        fi
        TAGS="${DOCKER_IMAGE}:${VERSION}"
        echo ::set-output name=version::${VERSION}
        echo ::set-output name=tags::${TAGS}
        echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
        echo ${VERSION}

  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
    - id: step1
      run: echo "::set-output name=test::hello"
    - id: step2
      run: echo "::set-output name=test::world"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
