name: Bump version

on:
  pull_request:
    types: [ closed ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: event_number
      shell: bash
      run: |
        echo "PR-number=${{ github.event.pull_request.number }}"

  tag:
    if: github.event.pull_request.merged == true
    name: bump tags
    outputs:
      part: ${{ steps.bump_tag.outputs.part }}
      tag: ${{ steps.bump_tag.outputs.tag }}
      new_tag: ${{ steps.bump_tag.outputs.new_tag }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '1'
    - name: Bump version and push tag
      id: bump_tag
      uses: anothrNick/github-tag-action@1.62.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch

  debug:
    needs: tag
    if: needs.tag.outputs.part != ''
    runs-on: ubuntu-latest
    steps:
      - name: event_number
        shell: bash
        run: |
          echo "PR-number=${{ github.event.pull_request.number }}"
          echo "github_ref=$GITHUB_REF"

  push_to_registry:
    needs: tag
    if: needs.tag.outputs.part != ''
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to the Github Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{raw}},value=${{ needs.tag.outputs.tag }}
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
